/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { connect, styled } from "frontity";
import React, { Fragment } from "react";
import ReactDOM from 'react-dom'
import GLTFGrabber from './GLTFGrabber'

const ModelViewer = ({ data }) => {
 return (<ModelViewerSection>
    <div>
    <GLTFGrabber data={data} />
    </div>
  </ModelViewerSection>

  );
};


export default connect(ModelViewer);

const ModelViewerSection = styled.section`
  background: white;
  color: black;
  margin: 0 0;
  padding: 0.5px 0;
  width: 100%;
  position:relative;
  overflow-x:hidden;
  @media(orientation:portrait){
    padding: 10px 0;
  }
`
