/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { connect, styled } from 'frontity'
import React, { Fragment } from 'react'
import ReactDOM from 'react-dom'
import GLTFGrabber from './GLTFGrabber'

const ModelViewer = ({ data }) => {
  return (
      <div>
        <GLTFGrabber data={data} />
      </div>
  )
}

export default connect(ModelViewer)



//ReactDOM.render(<ModelViewer data="./model.glb" />, document.getElementById('root'))
