/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { } from "frontity";
import React, { Component, } from "react";
import { connect, styled, css } from "frontity";
import { useGLTF, useAnimations } from '@react-three/drei'

const ModelViewer ({data}) =>{

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(data)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          geometry={nodes.Alpha_Joints.geometry}
          material={materials.Alpha_Joints_MAT}
          skeleton={nodes.Alpha_Joints.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface.geometry}
          material={materials.Alpha_Body_MAT}
          skeleton={nodes.Alpha_Surface.skeleton}
        />
      </group>
    </group>
    )
  }
};

useGLTF.preload(data)
