/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { connect, styled } from 'frontity'
import React, { Fragment } from 'react'
import ReactDOM from 'react-dom'
import GLTFGrabber from './GLTFGrabber'

const ModelViewer = ({ data1, data2, data3 }) => {
  return (
      <div>
        <GLTFGrabber data1={data1} data2={data2} data3={data3}/>

      </div>
  )
}

export default connect(ModelViewer)



//ReactDOM.render(<ModelViewer data="./model.glb" />, document.getElementById('root'))
